services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Effinix\UserPermissionBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,DependencyInversion,Entity}'
