services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  effinix.user_permission.logger.null:
    class: Psr\Log\NullLogger

  Effinix\UserPermissionBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,DependencyInversion,Entity}'
